Add xrf hdf5 exporter workflow
NSLS-II-SRX/workflows pull request #4
Opened 2024-04-26 19:51 UTC by hyperrealist

This PR adds XRF hdf5 exporter to `end_of_run_workflow`. The original non-Prefect exporter is available [here](https://github.com/andrewmkiss/srx-autosave/blob/b32427b6caab360b82991138cc4061b028e16e6b/srx_autosave/api.py#L376-L440).

2024-04-26 20:34 UTC, AbbyGi approved these changes
Looks good.

2024-04-26 20:55 UTC, jmaruland requested changes
It looks great. I added two small comments that are just quick fixes to improve the code.

2024-04-26 20:55 UTC, jmaruland commented on xrf_hdf5_exporter.py
> +    logger.info("Finish writing file.")
Now that we have two exporters being run from `end_of_run_workflow`, the log messages need to be specific to the type of exporter. Can you change the message to something like `"Start writing file with xrf_hdf5 exporter..."`?

2024-04-26 20:55 UTC, jmaruland commented on end_of_run_workflow.py
>      exporter(uid)
Now that we have two exporters, let's rename this method to help the reader identify and differentiate the two exporters. Something like `xanes_exporter` should be enough.

2024-05-06 20:12 UTC, jmaruland approved these changes

2024-05-10 07:17 UTC, hyperrealist commented
@AbbyGi, @jmaruland : this is ready for another review.

Local runs were successful on `2023-1.0-py310-tiled`.

2024-05-10 18:52 UTC, AbbyGi approved these changes
Looks good. We will definitely need to test with Prefect workers to make sure the overlay bit works as expected.

2024-06-20 17:46 UTC, merged